# Generated by Django 4.1.1 on 2023-07-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formatoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(default='p', max_length=1)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='top', max_length=6)),
                ('borde', models.BooleanField(default=False)),
                ('altura', models.SmallIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='formatoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.SmallIntegerField(default=1000)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='top', max_length=6)),
                ('borde', models.BooleanField(default=False)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear.formatoseccion')),
            ],
        ),
        migrations.CreateModel(
            name='formatoColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.SmallIntegerField(default=1000)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='top', max_length=6)),
                ('font_texto', models.CharField(default='Roboto,14,700', max_length=100)),
                ('color_texto', models.CharField(default='black', max_length=20)),
                ('justificacion_horizontal_texto', models.CharField(default='c', max_length=1)),
                ('justificacion_vertical_texto', models.CharField(default='c', max_length=1)),
                ('borde', models.BooleanField(default=False)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear.formatofila')),
            ],
        ),
    ]
