# Generated by Django 3.2.11 on 2022-01-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectotexto',
            name='texto',
            field=models.TextField(),
        ),
    ]
