# Generated by Django 3.2.11 on 2022-01-26 01:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyectotexto_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectotexto',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
