# Generated by Django 4.0.6 on 2022-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_proyectotexto_lineacontigua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(default='El proyecto '),
        ),
    ]
