# Generated by Django 4.0.6 on 2022-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='colortitulo',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
