# Generated by Django 4.0.6 on 2022-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_proyecto_segundocolorpaginaprincipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='degradehaciaarriba',
            field=models.BooleanField(default=False),
        ),
    ]
