# Generated by Django 4.0.6 on 2022-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_proyecto_colorfondomenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnabumederecha',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnabumeizquierda',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnabusqueda',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnaenderecha',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnaenizquierda',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnalogin',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnalogo',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnamenu',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altocolumnatitulo',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altofilabume',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='altofilaenizcede',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='bumecolorborde',
            field=models.CharField(default='#e0e0e0', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cencolorborde',
            field=models.CharField(default='#e0e0e0', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='colorcolumnapie',
            field=models.CharField(default='transparent', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='colorfilabume',
            field=models.CharField(default='transparent', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='colormenu',
            field=models.CharField(default='black', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='colortextovolver',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='degradehaciaarriba',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='enborde',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='encolorborde',
            field=models.CharField(default='#e0e0e0', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fontmenu',
            field=models.CharField(default='Open+Sans,12,400', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fonttextomedio',
            field=models.CharField(default='Roboto,12,500', max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fonttextovolver',
            field=models.CharField(default='Open+Sans,12,400', max_length=100),
        ),
    ]
