# Generated by Django 4.0.6 on 2022-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_seccionp_filap_columnap'),
    ]

    operations = [
        migrations.AddField(
            model_name='filap',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='seccionp',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
