# Generated by Django 4.1.1 on 2022-10-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_seccionp_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='conroles',
            field=models.BooleanField(default=False),
        ),
    ]
