# Generated by Django 4.1.1 on 2022-12-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_despliegaarbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnap',
            name='ingresosistema',
        ),
        migrations.AlterField(
            model_name='columnap',
            name='funcion',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
