# Generated by Django 4.1.1 on 2022-12-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_remove_columnap_ingresosistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='top', max_length=6)),
                ('borde', models.BooleanField(default=False)),
                ('altura', models.SmallIntegerField(default=1000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='main')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyectos.proyecto')),
            ],
        ),
        migrations.RenameModel(
            old_name='ColumnaP',
            new_name='Columna',
        ),
        migrations.RenameModel(
            old_name='FilaP',
            new_name='Fila',
        ),
        migrations.DeleteModel(
            name='SeccionP',
        ),
        migrations.AlterField(
            model_name='fila',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.seccion'),
        ),
    ]
