# Generated by Django 4.1.1 on 2022-12-13 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_seccion_rename_columnap_columna_rename_filap_fila_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seccion', to='proyectos.seccion'),
        ),
    ]
