# Generated by Django 4.1.1 on 2023-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0025_remove_proyectoobjeto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoobjeto',
            name='texto',
            field=models.TextField(),
        ),
    ]
