# Generated by Django 4.1.1 on 2023-02-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0028_alter_proyectoobjeto_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyectoObjeto',
        ),
    ]
