# Generated by Django 4.1.1 on 2023-02-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_proyectoobjeto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProyectoObjeto',
        ),
    ]
