# Generated by Django 4.1.1 on 2023-02-12 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0032_proyectoobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoobjeto',
            name='texto',
            field=ckeditor.fields.RichTextField(default='a'),
            preserve_default=False,
        ),
    ]
