# Generated by Django 4.1.1 on 2023-02-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0033_proyectoobjeto_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectoobjeto',
            old_name='texto',
            new_name='texto_objeto',
        ),
        migrations.RemoveField(
            model_name='proyectoobjeto',
            name='textoobjetos',
        ),
    ]
