# Generated by Django 4.1.1 on 2023-04-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0034_rename_texto_proyectoobjeto_texto_objeto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectotexto',
            old_name='texto',
            new_name='texto_texto',
        ),
    ]
