# Generated by Django 4.1.1 on 2023-07-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0035_rename_texto_proyectotexto_texto_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crear',
            name='despliega',
            field=models.BooleanField(default='False'),
        ),
    ]
