# Generated by Django 4.1.1 on 2023-07-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0036_crear_despliega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crear',
            name='despliega',
        ),
        migrations.AddField(
            model_name='crear',
            name='expand',
            field=models.BooleanField(default='True'),
        ),
    ]
