# Generated by Django 4.1.1 on 2023-07-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0039_crear_expand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crear',
            name='expand',
            field=models.CharField(default='expand', max_length=8),
        ),
    ]
