# Generated by Django 4.1.1 on 2023-08-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0043_alter_fila_altura_alter_seccion_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='dimensionesimagen',
            field=models.CharField(default='100%,100%', max_length=50),
        ),
        migrations.AddField(
            model_name='columna',
            name='margeninterno',
            field=models.CharField(default='0px', max_length=50),
        ),
    ]
