# Generated by Django 4.0.6 on 2022-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='font',
            field=models.CharField(default='Helvetica', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_columnas',
            field=models.CharField(default='Helvetica', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_columnas_size',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_encabezado',
            field=models.CharField(default='Helvetica', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_encabezado_size',
            field=models.SmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_size',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_titulo',
            field=models.CharField(default='Helvetica', max_length=100),
        ),
        migrations.AddField(
            model_name='modelo',
            name='font_titulo_size',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='modelo',
            name='margenes',
            field=models.CharField(default='20,20,20,20', max_length=20),
        ),
    ]
