# Generated by Django 4.0.6 on 2022-09-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_modelo_registrounico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='editarenlista',
            field=models.BooleanField(default=True),
        ),
    ]
