# Generated by Django 4.0.6 on 2022-09-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_modelo_editarenlista'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='treeview',
            field=models.BooleanField(default=False),
        ),
    ]
