# Generated by Django 4.0.6 on 2022-09-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0008_modelo_treeview'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colorfondotreeview',
            field=models.CharField(default='#0375B4', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortreeview',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='columnastreeview',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fonttreeview',
            field=models.CharField(default='Open+Sans,8,normal', max_length=100),
        ),
    ]
