# Generated by Django 4.0.6 on 2022-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0010_seccion_fila_columna'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
