# Generated by Django 4.1.1 on 2022-10-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0011_fila_nombre_seccion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='usabaseparticular',
            field=models.BooleanField(default=False),
        ),
    ]
