# Generated by Django 4.1.1 on 2022-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0012_modelo_usabaseparticular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
