# Generated by Django 4.1.1 on 2022-11-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0015_remove_columna_ingresosistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columna',
            name='borde',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='colortexto',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='degradado',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='fonttexto',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='justificacionhorizontaltexto',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='justificacionverticaltexto',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='secciones',
        ),
        migrations.RemoveField(
            model_name='columna',
            name='textocolumna',
        ),
    ]
