# Generated by Django 4.1.1 on 2022-11-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0017_columna_color1_columna_color2_columna_degradado'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='main'),
        ),
    ]
