# Generated by Django 4.1.1 on 2022-11-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0018_columna_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='colortexto',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='columna',
            name='fonttexto',
            field=models.CharField(default='Roboto,14,700', max_length=100),
        ),
        migrations.AddField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='columna',
            name='secciones',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='columna',
            name='textocolumna',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
