# Generated by Django 4.1.1 on 2022-11-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0020_remove_columna_justificacionhorizontaltexto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='borde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='columna',
            name='funcion',
            field=models.CharField(default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
