# Generated by Django 4.1.1 on 2023-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0023_seccion_fila_columna'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonaid', models.SmallIntegerField()),
                ('propid', models.SmallIntegerField()),
                ('width', models.SmallIntegerField()),
                ('left', models.SmallIntegerField()),
            ],
        ),
    ]
