# Generated by Django 4.1.1 on 2023-03-03 15:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0025_zonareporte_modeloid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonareporte',
            name='left',
        ),
        migrations.RemoveField(
            model_name='zonareporte',
            name='modeloid',
        ),
        migrations.RemoveField(
            model_name='zonareporte',
            name='propid',
        ),
        migrations.RemoveField(
            model_name='zonareporte',
            name='width',
        ),
        migrations.RemoveField(
            model_name='zonareporte',
            name='zonaid',
        ),
        migrations.AddField(
            model_name='zonareporte',
            name='modelo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zonareporte',
            name='texto',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
