# Generated by Django 4.1.1 on 2023-03-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0026_remove_zonareporte_left_remove_zonareporte_modeloid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonareporte',
            old_name='modelo',
            new_name='modeloid',
        ),
    ]
