# Generated by Django 4.1.1 on 2023-03-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0027_rename_modelo_zonareporte_modeloid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='font',
            field=models.CharField(default='Helvetica,10,500', max_length=100),
        ),
    ]
