# Generated by Django 4.1.1 on 2023-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0028_alter_modelo_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonareporte',
            name='texto',
            field=models.TextField(),
        ),
    ]
