# Generated by Django 4.1.1 on 2023-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0029_alter_zonareporte_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaReporteAdHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('modeloid', models.IntegerField(default=0)),
            ],
        ),
    ]
