# Generated by Django 4.1.1 on 2023-03-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0031_reporteadhocobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteadhocobjeto',
            name='codigo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelo',
            name='font_columnas',
            field=models.CharField(default='Helvetica,10,500', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='font_encabezado',
            field=models.CharField(default='Helvetica,10,500', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='font_titulo',
            field=models.CharField(default='Helvetica,10,500', max_length=100),
        ),
    ]
