# Generated by Django 4.1.1 on 2023-03-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0032_reporteadhocobjeto_codigo_alter_modelo_font_columnas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonareporte',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
