# Generated by Django 4.1.1 on 2023-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0033_zonareporte_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteadhocobjeto',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
