# Generated by Django 4.1.1 on 2023-04-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0034_reporteadhocobjeto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='datoinicialx',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='fechax',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='lineafx',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='lineaix',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='titulox',
        ),
    ]
