# Generated by Django 4.1.1 on 2023-04-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0036_remove_modelo_identacionautomatica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='font_columnas_size',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='font_encabezado_size',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='font_titulo_size',
        ),
    ]
