# Generated by Django 4.1.1 on 2023-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0037_remove_modelo_font_columnas_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='font_totales',
            field=models.CharField(default='Helvetica-Bold,10,500', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='font_columnas',
            field=models.CharField(default='Helvetica-Bold,10,500', max_length=100),
        ),
    ]
