# Generated by Django 4.1.1 on 2023-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0039_alter_modelo_font_columnas_alter_modelo_font_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='identa',
            field=models.SmallIntegerField(default=1),
        ),
    ]
