# Generated by Django 4.1.1 on 2023-06-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0040_modelo_identa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='', max_length=30)),
                ('modeloid', models.IntegerField(default=0)),
                ('codigo', models.TextField()),
            ],
        ),
    ]
