# Generated by Django 4.1.1 on 2023-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0041_dashobjeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='dimensioneslogo',
            field=models.CharField(default='15,15', max_length=15),
        ),
    ]
