# Generated by Django 4.1.1 on 2023-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0042_modelo_dimensioneslogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='nivelidentacion',
            field=models.SmallIntegerField(default=1),
        ),
    ]
