# Generated by Django 4.1.1 on 2023-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0043_modelo_nivelidentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='ultimoregistro',
            field=models.CharField(default='p', max_length=1),
        ),
    ]
