# Generated by Django 4.1.1 on 2023-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0044_alter_modelo_ultimoregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='c', max_length=6),
        ),
        migrations.AlterField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='c', max_length=6),
        ),
    ]
