# Generated by Django 4.1.1 on 2023-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0045_alter_columna_justificacionhorizontaltexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='center', max_length=6),
        ),
        migrations.AlterField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='center', max_length=6),
        ),
    ]
