# Generated by Django 4.1.1 on 2023-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0046_alter_columna_justificacionhorizontaltexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='altura',
            field=models.CharField(default='100px', max_length=20),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='altura',
            field=models.CharField(default='1000px', max_length=20),
        ),
    ]
