# Generated by Django 4.1.1 on 2023-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0048_modelo_saltopagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='grosorlineaencabezado',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
