# Generated by Django 4.1.1 on 2023-08-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0049_modelo_grosorlineaencabezado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='colorcolumnas',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colorencabezado',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortexto',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortitulo',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='modelo',
            name='colortotales',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
