# Generated by Django 4.1.1 on 2023-08-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0053_modelo_mayusculastituloborra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='bordeexteriorborra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeexteriorinserta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeexteriorlista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeexteriorupdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeformularioborra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeformularioinserta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelo',
            name='bordeformularioupdate',
            field=models.BooleanField(default=False),
        ),
    ]
