# Generated by Django 4.1.1 on 2023-08-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0054_modelo_bordeexteriorborra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='bordeformularioborra',
        ),
    ]
