# Generated by Django 4.1.1 on 2023-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0055_remove_modelo_bordeformularioborra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='altofilatituloborra',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='altofilatituloinserta',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='altofilatituloupdate',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='altotitulolista',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='bordecomentarioborra',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='bordecomentarioinserta',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='bordecomentariolista',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='bordecomentarioupdate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='colorcolumnaslista',
            field=models.CharField(default='#505050', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='colorfondocolumnaslista',
            field=models.CharField(default='#e8eaed', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='colorfondocomentarioborra',
            field=models.CharField(default='#f5f5f5', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='colorfondocomentarioinserta',
            field=models.CharField(default='#f5f5f5', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='colorfondocomentariolista',
            field=models.CharField(default='#f5f5f5', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='colorfondocomentarioupdate',
            field=models.CharField(default='#f5f5f5', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fontcolumnaslista',
            field=models.CharField(default='Roboto,11,700', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fonttituloborra',
            field=models.CharField(default='Arvo,20,700', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fonttituloinserta',
            field=models.CharField(default='Arvo,20,700', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fonttitulolista',
            field=models.CharField(default='Arvo,20,700', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fonttituloupdate',
            field=models.CharField(default='Arvo,20,700', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='textoeditarborrar',
            field=models.CharField(default='Edita,Borra', max_length=30),
        ),
    ]
