# Generated by Django 3.2.11 on 2022-01-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('textoenmenu', models.CharField(blank=True, default='', max_length=30)),
                ('imagenmenu', models.ImageField(blank=True, null=True, upload_to='proyectos')),
                ('tooltip', models.CharField(blank=True, default='', max_length=30)),
                ('ordengeneracion', models.SmallIntegerField(default=1)),
                ('homelogin', models.BooleanField(default=False)),
                ('homestaff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
    ]
