# Generated by Django 4.0.6 on 2022-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_alter_aplicacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='fontmenu',
            field=models.CharField(default='Open+Sans,10,400', max_length=100),
        ),
    ]
