# Generated by Django 4.0.6 on 2022-08-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0011_alter_proyecto_altocolumnabumederecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='u', max_length=1)),
                ('imagen', models.ImageField(upload_to='')),
                ('texto', models.TextField(default='El modelo ')),
                ('fonttexto', models.CharField(default='Roboto,14,700', max_length=100)),
                ('colortexto', models.CharField(default='black', max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('altura', models.SmallIntegerField(default=10)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='u', max_length=1)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('color1', models.CharField(default='transparent', max_length=20)),
                ('color2', models.CharField(default='transparent', max_length=20)),
                ('degradado', models.CharField(default='u', max_length=1)),
                ('imagencolumna', models.ImageField(blank=True, null=True, upload_to='main')),
                ('secciones', models.SmallIntegerField(default=10)),
                ('texto', models.TextField(default='El modelo ')),
                ('fonttexto', models.CharField(default='Roboto,14,700', max_length=100)),
                ('colortexto', models.CharField(default='black', max_length=20)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.fila')),
            ],
        ),
    ]
