# Generated by Django 4.0.6 on 2022-08-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columna',
            old_name='imagencolumna',
            new_name='imagen',
        ),
    ]
