# Generated by Django 4.0.6 on 2022-08-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_rename_imagencolumna_columna_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='main'),
        ),
    ]
