# Generated by Django 4.0.6 on 2022-08-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_seccion_texto_seccion_textoseccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columna',
            old_name='texto',
            new_name='textocolumna',
        ),
    ]
