# Generated by Django 4.0.6 on 2022-08-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_rename_texto_columna_textocolumna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='textocolumna',
            field=models.TextField(default=''),
        ),
    ]
