# Generated by Django 4.0.6 on 2022-08-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_columna_textocolumna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='degradado',
            field=models.CharField(default='top', max_length=5),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='degradado',
            field=models.CharField(default='top', max_length=5),
        ),
    ]
