# Generated by Django 4.0.6 on 2022-08-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_alter_fila_degradado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='textocolumna',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='textoseccion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
