# Generated by Django 4.0.6 on 2022-08-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alter_columna_textocolumna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='seccion',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='seccion',
            name='justificacionverticaltexto',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
