# Generated by Django 4.0.6 on 2022-08-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_columna_justificacionhorizontaltexto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='center', max_length=6),
        ),
        migrations.AlterField(
            model_name='columna',
            name='justificacionverticaltexto',
            field=models.CharField(default='center', max_length=6),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='justificacionhorizontaltexto',
            field=models.CharField(default='center', max_length=6),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='justificacionverticaltexto',
            field=models.CharField(default='center', max_length=8),
        ),
    ]
