# Generated by Django 4.0.6 on 2022-08-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_alter_columna_justificacionhorizontaltexto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='colortexto',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='fonttexto',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='justificacionhorizontaltexto',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='justificacionverticaltexto',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='textoseccion',
        ),
    ]
