# Generated by Django 4.0.6 on 2022-08-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_remove_seccion_colortexto_remove_seccion_fonttexto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='imagen',
        ),
    ]
