# Generated by Django 4.0.6 on 2022-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_remove_seccion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='borde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fila',
            name='borde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seccion',
            name='borde',
            field=models.BooleanField(default=False),
        ),
    ]
