# Generated by Django 4.1.1 on 2022-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_seccion_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='funcion',
            field=models.CharField(default='o', max_length=1),
        ),
    ]
