# Generated by Django 4.1.1 on 2022-12-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_seccion_rename_columnap_columna_rename_filap_fila_and_more'),
        ('principal', '0019_remove_columna_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='proyectos.proyecto'),
        ),
    ]
