# Generated by Django 4.1.1 on 2023-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_alter_seccion_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila',
            name='altura',
            field=models.CharField(default='10%', max_length=20),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='altura',
            field=models.CharField(default='1000px', max_length=20),
        ),
    ]
