# Generated by Django 4.1.1 on 2023-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_alter_fila_altura_alter_seccion_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='columna',
            name='dimensionesimagen',
            field=models.CharField(default='100%,100%', max_length=50),
        ),
    ]
