# Generated by Django 4.1.1 on 2023-08-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_columna_margeninterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columna',
            name='margeninterno',
            field=models.CharField(default='0px', max_length=50),
        ),
    ]
