# Generated by Django 4.0.6 on 2022-07-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='anchoenreporte',
            field=models.SmallIntegerField(default=100),
        ),
    ]
