# Generated by Django 4.0.6 on 2022-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_anchoenreporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='enreporte',
            field=models.BooleanField(default=True),
        ),
    ]
