# Generated by Django 4.0.6 on 2022-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_alter_propiedad_enreporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(default='La propiedad '),
        ),
    ]
