# Generated by Django 4.0.6 on 2022-08-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_propiedad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='enlista',
            field=models.BooleanField(default=True),
        ),
    ]
