# Generated by Django 4.0.6 on 2022-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_alter_propiedad_enlista'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='linkparaedicion',
            field=models.BooleanField(default=True),
        ),
    ]
