# Generated by Django 4.0.6 on 2022-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_alter_propiedad_linkparaedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
