# Generated by Django 4.1.1 on 2022-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_propiedad_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='paraborrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='paraidentificar',
            field=models.BooleanField(default=False),
        ),
    ]
