# Generated by Django 4.1.1 on 2023-03-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0009_propiedad_paraborrar_propiedad_paraidentificar'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='paratotalizar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propiedadtotaliza',
            field=models.CharField(default='', max_length=30),
        ),
    ]
