# Generated by Django 4.1.1 on 2023-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0010_propiedad_paratotalizar_propiedad_propiedadtotaliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='propiedadtotaliza',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
