# Generated by Django 4.1.1 on 2023-04-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0011_alter_propiedad_propiedadtotaliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='alineacion',
            field=models.CharField(default='l', max_length=1),
        ),
    ]
