# Generated by Django 4.1.1 on 2023-07-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0012_propiedad_alineacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='camposfill',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
