# Generated by Django 4.1.1 on 2023-07-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0013_propiedad_camposfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fillunico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='camposfill',
            field=models.TextField(blank=True, default=''),
        ),
    ]
