# Generated by Django 4.1.1 on 2023-07-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0014_propiedad_fillunico_alter_propiedad_camposfill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='camposfill',
            new_name='prefijofill',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fillunico',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='valoreselegir',
            field=models.SmallIntegerField(default=1),
        ),
    ]
